package com.play.app.type;

public enum MasterType {

	MASTER_EXPENSE_HEAD("EXPENSE_HEAD"), 
	MASTER_DESIGNATION("DESIGNATION"), 
	MASTER_AREA_DUBAI("AREA_DUBAI"), 
	MASTER_AREA_SHARJAH("AREA_SHARJAH"),
	MASTER_NATIONALITY("NATIONALITY"),
	BOOKING_SLOT_OPTIONS("BOOKING_SLOT_OPTIONS"),
	VEHICLE_MAKE("VEHICLE_MAKE"),
	EMIRATE("EMIRATE"),
	EMAIL_SETTINGS("EMAIL_SETTINGS"),
	CORE_SETTINGS("CORE_SETTINGS"),
	PAYMENT_GATEWAY_SETTINGS("PAYMENT_GATEWAY_SETTINGS"),
	PUSH_NOTIFICATIONS_SETTINGS("PUSH_NOTIFICATIONS_SETTINGS"),
	SMS_SETTINGS("SMS_SETTINGS"),
	SERVICE_QUALITY_SETTINGS("SERVICE_QUALITY_SETTINGS");
	
	private String masterType;

	private MasterType(String masterType) {
		this.masterType = masterType;
	}

	public String getMasterType() {
		return this.masterType;
	}
}